use eframe::egui;

#[derive(Default)]
pub struct CodegenView {
    pub generated_code: String,
    pub copy_status: Option<String>,
}

impl CodegenView {
    pub fn new() -> Self {
        let sample_code = r#"//! Auto-generated by embedded-nn-studio. Zero-allocation #![no_std].
use embedded_nn::{
    Activation, Dims, FcParams, PerTensorQuantParams,
    fully_connected_s4, softmax_s8,
};

pub const ARENA_SIZE_BYTES: usize = 512;
pub const FLASH_WEIGHTS_BYTES: usize = 4280;

static FC1_WEIGHTS_S4: [i8; 128] = [
    0x23, 0x1f, 0x04, -118, 0x12, 0x34, 0x56, 0x78, 
    -102, -68, -34, -16, 0x11, 0x22, 0x33, 0x44,
];

pub struct GestureClassifier;

impl GestureClassifier {
    pub const INPUT_DIM: usize = 32;
    pub const OUTPUT_DIM: usize = 4;
    pub const ARENA_SIZE: usize = ARENA_SIZE_BYTES;

    pub fn predict<'a>(
        input: &[i8],
        arena: &'a mut [u8; ARENA_SIZE_BYTES],
    ) -> Result<&'a [i8], &'static str> {
        let fc_params = FcParams {
            input_offset: 0,
            filter_offset: 0,
            output_offset: 0,
            activation: Activation::int8_unconstrained(),
        };
        let quant_params = PerTensorQuantParams::new(1073741824, 0);

        let in_buf = &input[..32];
        let out_buf = unsafe { core::slice::from_raw_parts_mut(arena.as_mut_ptr() as *mut i8, 4) };

        fully_connected_s4(
            &fc_params,
            &quant_params,
            &Dims::new(1, 1, 1, 32),
            in_buf,
            &Dims::new(4, 1, 1, 1),
            &FC1_WEIGHTS_S4,
            None,
            &Dims::new(1, 1, 1, 4),
            out_buf,
        ).map_err(|_| "FC failed")?;

        Ok(out_buf)
    }
}
"#
        .into();

        Self {
            generated_code: sample_code,
            copy_status: None,
        }
    }

    pub fn show(&mut self, ui: &mut egui::Ui) {
        ui.heading("5. Zero-Allocation #![no_std] Rust Code Generator");
        ui.add_space(8.0);

        ui.horizontal(|ui| {
            if ui.button("📋 Copy Rust Code").clicked() {
                ui.ctx().copy_text(self.generated_code.clone());
                self.copy_status = Some("Code copied to clipboard!".into());
            }

            if ui.button("💾 Export to src/model.rs").clicked() {
                self.copy_status = Some("Saved to src/model.rs".into());
            }

            if let Some(status) = &self.copy_status {
                ui.label(status);
            }
        });

        ui.add_space(8.0);
        ui.separator();

        egui::ScrollArea::vertical().show(ui, |ui| {
            ui.add(
                egui::TextEdit::multiline(&mut self.generated_code)
                    .font(egui::TextStyle::Monospace)
                    .code_editor()
                    .lock_focus(true)
                    .desired_width(f32::INFINITY),
            );
        });
    }
}
