[package]
name = "embedded-nn"
version = "0.2.0"
edition = "2021"
authors = ["Gerzain Mata <leftger@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/leftger/embedded-nn"
description = "A pure Rust, #![no_std] neural network inference library inspired by CMSIS-NN for microcontrollers and embedded targets."
readme = "README.md"
keywords = ["no-std", "embedded", "cmsis-nn", "neural-network", "quantization"]
categories = ["embedded", "science", "no-std"]

[features]
default = ["libm"]
alloc = []
float = []
simd = []
libm = ["dep:libm"]

[dependencies]
libm = { version = "0.2.11", optional = true }

[dev-dependencies]
