ignore:
  - "embedded-nn-cli/**"
  - "crates/embedded-nn-cli/**"
  - "embedded-nn-studio/**"
  - "crates/embedded-nn-studio/**"
  - "embedded-nn-tflite/schema/**"
  - "crates/embedded-nn-tflite/schema/**"
  - "**/schema_generated.rs"
  - "examples/**"
  - "analysis/**"
  - "assets/**"
  - "docs/**"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 60%
        threshold: 1%
