use embedded_nn_compiler::ir::*;
use std::fmt::Write;

pub struct CCodeGenerator {
    pub model_name: String,
}

impl CCodeGenerator {
    pub fn new(model_name: impl Into<String>) -> Self {
        Self {
            model_name: model_name.into(),
        }
    }

    pub fn generate(&self, graph: &ModelGraph) -> String {
        let mut out = String::new();
        writeln!(out, "/* Auto-generated by embedded-nn C code generator */").unwrap();
        writeln!(out, "#ifndef {}_H", self.model_name.to_uppercase()).unwrap();
        writeln!(out, "#define {}_H", self.model_name.to_uppercase()).unwrap();
        writeln!(out, "\n#include <stdint.h>\n#include <stddef.h>\n").unwrap();

        writeln!(
            out,
            "#define {}_ARENA_SIZE_BYTES {}",
            self.model_name.to_uppercase(),
            graph.inputs.len() * 64
        )
        .unwrap();
        writeln!(out, "\nvoid {}_init(void);", self.model_name.to_lowercase()).unwrap();
        writeln!(
            out,
            "void {}_predict(const int8_t* input, int8_t* output);\n",
            self.model_name.to_lowercase()
        )
        .unwrap();
        writeln!(out, "#endif /* {}_H */", self.model_name.to_uppercase()).unwrap();

        out
    }
}
