//! C99 standalone header-only code generator for `embedded-nn`.
//!
//! Emits self-contained C99 code with static weights, fixed-point math helpers,
//! and static arena memory indexing for STM32CubeIDE, Keil MDK, and C/C++ firmware.

use embedded_nn_compiler::arena::ArenaScheduler;
use embedded_nn_compiler::ir::*;
use std::fmt::Write;

pub struct CCodeGenerator {
    pub model_name: String,
}

impl CCodeGenerator {
    pub fn new(model_name: impl Into<String>) -> Self {
        Self {
            model_name: model_name.into(),
        }
    }

    pub fn generate(&self, graph: &ModelGraph) -> String {
        let arena = ArenaScheduler::schedule(graph);
        let name_upper = self.model_name.to_uppercase();
        let name_lower = self.model_name.to_lowercase();
        let in_elements = if !graph.inputs.is_empty() {
            graph.tensors[graph.inputs[0]].shape.total_elements()
        } else {
            1
        };
        let out_elements = if !graph.outputs.is_empty() {
            graph.tensors[graph.outputs[0]].shape.total_elements()
        } else {
            1
        };

        let mut out = String::new();
        writeln!(
            out,
            "/* ==========================================================================="
        )
        .unwrap();
        writeln!(out, " * Auto-generated by embedded-nn C99 Code Generator").unwrap();
        writeln!(out, " * Model: {}", self.model_name).unwrap();
        writeln!(
            out,
            " * Zero dynamic allocation. Fully static arena execution."
        )
        .unwrap();
        writeln!(
            out,
            " * =========================================================================== */\n"
        )
        .unwrap();

        writeln!(out, "#ifndef {}_H", name_upper).unwrap();
        writeln!(out, "#define {}_H\n", name_upper).unwrap();
        writeln!(out, "#include <stdint.h>").unwrap();
        writeln!(out, "#include <stddef.h>").unwrap();
        writeln!(out, "#include <stdbool.h>\n").unwrap();

        writeln!(out, "#ifdef __cplusplus").unwrap();
        writeln!(out, "extern \"C\" {{").unwrap();
        writeln!(out, "#endif\n").unwrap();

        let in_shape = if !graph.inputs.is_empty() {
            graph.tensors[graph.inputs[0]].shape
        } else {
            TensorShape::new_1d(1)
        };
        let out_shape = if !graph.outputs.is_empty() {
            graph.tensors[graph.outputs[0]].shape
        } else {
            TensorShape::new_1d(1)
        };

        writeln!(out, "#define {}_INPUT_DIM {}", name_upper, in_elements).unwrap();
        writeln!(out, "#define {}_OUTPUT_DIM {}", name_upper, out_elements).unwrap();
        writeln!(
            out,
            "#define {}_INPUT_SHAPE_N {}",
            name_upper, in_shape.batches
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_INPUT_SHAPE_H {}",
            name_upper, in_shape.height
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_INPUT_SHAPE_W {}",
            name_upper, in_shape.width
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_INPUT_SHAPE_C {}",
            name_upper, in_shape.channels
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_OUTPUT_SHAPE_N {}",
            name_upper, out_shape.batches
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_OUTPUT_SHAPE_H {}",
            name_upper, out_shape.height
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_OUTPUT_SHAPE_W {}",
            name_upper, out_shape.width
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_OUTPUT_SHAPE_C {}",
            name_upper, out_shape.channels
        )
        .unwrap();
        writeln!(
            out,
            "#define {}_ARENA_SIZE_BYTES {}",
            name_upper,
            arena.total_arena_bytes.max(64)
        )
        .unwrap();
        writeln!(out, "#define {}_ARENA_ALIGNMENT 4\n", name_upper).unwrap();

        // Fixed-point C helpers
        writeln!(out, "/* --- Fixed-Point Math Helpers --- */").unwrap();
        writeln!(
            out,
            "static inline int32_t {}_clamp(int32_t val, int32_t min, int32_t max) {{",
            name_lower
        )
        .unwrap();
        writeln!(out, "    if (val < min) return min;").unwrap();
        writeln!(out, "    if (val > max) return max;").unwrap();
        writeln!(out, "    return val;").unwrap();
        writeln!(out, "}}\n").unwrap();

        writeln!(out, "static inline int32_t {}_requantize(int32_t val, int32_t multiplier, int32_t shift) {{", name_lower).unwrap();
        writeln!(
            out,
            "    int64_t total = (int64_t)val * (int64_t)multiplier + (1LL << 30);"
        )
        .unwrap();
        writeln!(out, "    int32_t mult = (int32_t)(total >> 31);").unwrap();
        writeln!(out, "    if (shift >= 0) {{").unwrap();
        writeln!(out, "        return mult << shift;").unwrap();
        writeln!(out, "    }} else {{").unwrap();
        writeln!(out, "        int32_t right = -shift;").unwrap();
        writeln!(out, "        int32_t mask = (1 << right) - 1;").unwrap();
        writeln!(out, "        int32_t remainder = mult & mask;").unwrap();
        writeln!(out, "        int32_t res = mult >> right;").unwrap();
        writeln!(out, "        if (remainder > (mask >> 1)) res += 1;").unwrap();
        writeln!(out, "        return res;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}\n").unwrap();

        // Emit model weights
        writeln!(out, "/* --- Layer Weights & Constants --- */").unwrap();
        for (i, layer) in graph.layers.iter().enumerate() {
            match &layer.op {
                OpPayload::FullyConnected { weights, bias, .. } => {
                    writeln!(
                        out,
                        "static const int8_t {}_layer_{}_weights[{}] = {{",
                        name_lower,
                        i,
                        weights.len()
                    )
                    .unwrap();
                    for (w_idx, w) in weights.iter().enumerate() {
                        write!(out, "{}, ", w).unwrap();
                        if (w_idx + 1) % 16 == 0 {
                            writeln!(out).unwrap();
                        }
                    }
                    writeln!(out, "}};\n").unwrap();

                    if let Some(b) = bias {
                        writeln!(
                            out,
                            "static const int32_t {}_layer_{}_bias[{}] = {{",
                            name_lower,
                            i,
                            b.len()
                        )
                        .unwrap();
                        for (b_idx, val) in b.iter().enumerate() {
                            write!(out, "{}, ", val).unwrap();
                            if (b_idx + 1) % 8 == 0 {
                                writeln!(out).unwrap();
                            }
                        }
                        writeln!(out, "}};\n").unwrap();
                    }
                }
                OpPayload::Conv2D { weights, bias, .. } => {
                    writeln!(
                        out,
                        "static const int8_t {}_layer_{}_conv_weights[{}] = {{",
                        name_lower,
                        i,
                        weights.len()
                    )
                    .unwrap();
                    for (w_idx, w) in weights.iter().enumerate() {
                        write!(out, "{}, ", w).unwrap();
                        if (w_idx + 1) % 16 == 0 {
                            writeln!(out).unwrap();
                        }
                    }
                    writeln!(out, "}};\n").unwrap();

                    if let Some(b) = bias {
                        writeln!(
                            out,
                            "static const int32_t {}_layer_{}_conv_bias[{}] = {{",
                            name_lower,
                            i,
                            b.len()
                        )
                        .unwrap();
                        for (b_idx, val) in b.iter().enumerate() {
                            write!(out, "{}, ", val).unwrap();
                            if (b_idx + 1) % 8 == 0 {
                                writeln!(out).unwrap();
                            }
                        }
                        writeln!(out, "}};\n").unwrap();
                    }
                }
                _ => {}
            }
        }

        // Emit inference entrypoint function
        writeln!(out, "/* --- Predict Entrypoint --- */").unwrap();
        writeln!(
            out,
            "static inline int {}_predict(const int8_t* input, int8_t* output, uint8_t* arena) {{",
            name_lower
        )
        .unwrap();
        writeln!(out, "    if (!input || !output || !arena) return -1;\n").unwrap();

        for (i, layer) in graph.layers.iter().enumerate() {
            writeln!(out, "    /* Layer {}: {} */", i, layer.name).unwrap();
            match &layer.op {
                OpPayload::FullyConnected {
                    weights: _, bias, ..
                } => {
                    let in_id = layer.inputs[0];
                    let out_id = layer.outputs[0];
                    let in_offset = arena.offset_of(in_id).unwrap_or(0);
                    let out_offset = arena.offset_of(out_id).unwrap_or(0);
                    let out_depth = graph.tensors[out_id].shape.total_elements();
                    let in_depth = graph.tensors[in_id].shape.total_elements();

                    writeln!(out, "    {{").unwrap();
                    if graph.inputs.contains(&in_id) {
                        writeln!(out, "        const int8_t* l_in = input;").unwrap();
                    } else {
                        writeln!(
                            out,
                            "        const int8_t* l_in = (const int8_t*)(arena + {});",
                            in_offset
                        )
                        .unwrap();
                    }
                    if graph.outputs.contains(&out_id) {
                        writeln!(out, "        int8_t* l_out = output;").unwrap();
                    } else {
                        writeln!(
                            out,
                            "        int8_t* l_out = (int8_t*)(arena + {});",
                            out_offset
                        )
                        .unwrap();
                    }
                    writeln!(
                        out,
                        "        for (size_t oc = 0; oc < {}; oc++) {{",
                        out_depth
                    )
                    .unwrap();
                    if bias.is_some() {
                        writeln!(
                            out,
                            "            int32_t acc = {}_layer_{}_bias[oc];",
                            name_lower, i
                        )
                        .unwrap();
                    } else {
                        writeln!(out, "            int32_t acc = 0;").unwrap();
                    }
                    writeln!(
                        out,
                        "            const int8_t* w_row = &{}_layer_{}_weights[oc * {}];",
                        name_lower, i, in_depth
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "            for (size_t ic = 0; ic < {}; ic++) {{",
                        in_depth
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "                acc += (int32_t)l_in[ic] * (int32_t)w_row[ic];"
                    )
                    .unwrap();
                    writeln!(out, "            }}").unwrap();
                    let q = &graph.tensors[out_id].quant;
                    writeln!(
                        out,
                        "            acc = {}_requantize(acc, {}, {});",
                        name_lower, q.multiplier, q.shift
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "            l_out[oc] = (int8_t){}_clamp(acc + {}, -128, 127);",
                        name_lower, q.zero_point
                    )
                    .unwrap();
                    writeln!(out, "        }}").unwrap();
                    writeln!(out, "    }}\n").unwrap();
                }
                OpPayload::Softmax => {
                    let _in_id = layer.inputs[0];
                    let out_id = layer.outputs[0];
                    let out_depth = graph.tensors[out_id].shape.total_elements();
                    writeln!(out, "    {{").unwrap();
                    if graph.outputs.contains(&out_id) {
                        writeln!(out, "        int8_t* l_out = output;").unwrap();
                    } else {
                        let out_offset = arena.offset_of(out_id).unwrap_or(0);
                        writeln!(
                            out,
                            "        int8_t* l_out = (int8_t*)(arena + {});",
                            out_offset
                        )
                        .unwrap();
                    }
                    writeln!(out, "        int8_t max_val = l_out[0];").unwrap();
                    writeln!(out, "        for (size_t c = 1; c < {}; c++) if (l_out[c] > max_val) max_val = l_out[c];", out_depth).unwrap();
                    writeln!(
                        out,
                        "        for (size_t c = 0; c < {}; c++) l_out[c] -= max_val;",
                        out_depth
                    )
                    .unwrap();
                    writeln!(out, "    }}\n").unwrap();
                }
                _ => {}
            }
        }

        writeln!(out, "    return 0;").unwrap();
        writeln!(out, "}}\n").unwrap();
        writeln!(out, "#ifdef __cplusplus").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out, "#endif\n").unwrap();
        writeln!(out, "#endif /* {}_H */", name_upper).unwrap();

        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use embedded_nn_compiler::builder::ModelBuilder;

    #[test]
    fn test_c_code_generator_dense() {
        let mut builder = ModelBuilder::new("GestureModel");
        let quant = QuantParams {
            multiplier: 1073741824,
            shift: 0,
            zero_point: 0,
            scale: 1.0 / 127.0,
        };
        let in_id = builder.add_input(
            "in",
            TensorShape::new_1d(16),
            DataType::Int8,
            Some(quant.clone()),
        );
        let weights = vec![1i8; 16 * 4];
        let bias = vec![0i32; 4];
        let fc_id = builder.add_dense_layer(
            "fc",
            in_id,
            4,
            weights,
            None,
            Some(bias),
            ActivationType::None,
            None,
            Some(quant),
        );
        builder.mark_output(fc_id);

        let graph = builder.build();
        let generator = CCodeGenerator::new("GestureModel");
        let c_code = generator.generate(&graph);

        assert!(c_code.contains("#define GESTUREMODEL_INPUT_DIM 16"));
        assert!(c_code.contains("#define GESTUREMODEL_OUTPUT_DIM 4"));
        assert!(c_code.contains("#define GESTUREMODEL_INPUT_SHAPE_C 16"));
        assert!(c_code.contains("#define GESTUREMODEL_OUTPUT_SHAPE_C 4"));
        assert!(c_code.contains(
            "int gesturemodel_predict(const int8_t* input, int8_t* output, uint8_t* arena)"
        ));
    }
}
