use embedded_nn_compiler::arena::ArenaScheduler;
use embedded_nn_compiler::ir::*;

pub struct RustCodeGenerator {
    struct_name: String,
}

impl RustCodeGenerator {
    pub fn new(struct_name: impl Into<String>) -> Self {
        Self {
            struct_name: struct_name.into(),
        }
    }

    pub fn generate(&self, graph: &ModelGraph) -> String {
        let arena_plan = ArenaScheduler::schedule(graph);
        let mut out = String::new();

        out.push_str("//! Auto-generated by embedded-nn-codegen. DO NOT EDIT MANUALLY.\n");
        out.push_str("//! Zero-allocation #![no_std] neural network inference pipeline.\n\n");
        out.push_str("use embedded_nn::{\n");
        out.push_str("    Activation, Dims, FcParams, PerTensorQuantParams,\n");
        out.push_str("    fully_connected_s8, fully_connected_s4, softmax_s8,\n");
        out.push_str("};\n\n");

        let arena_size = arena_plan.total_arena_bytes;
        let weights_size = graph.total_weights_size_bytes();

        out.push_str(&format!(
            "pub const ARENA_SIZE_BYTES: usize = {};\n",
            arena_size
        ));
        out.push_str(&format!(
            "pub const FLASH_WEIGHTS_BYTES: usize = {};\n\n",
            weights_size
        ));

        // Emit static weight constants
        for layer in &graph.layers {
            let prefix = layer.name.to_uppercase();
            match &layer.op {
                OpPayload::FullyConnected {
                    weights,
                    packed_s4,
                    bias,
                    ..
                } => {
                    if let Some(s4) = packed_s4 {
                        out.push_str(&format!(
                            "static {}_WEIGHTS_S4: [i8; {}] = [\n    ",
                            prefix,
                            s4.len()
                        ));
                        for (i, byte) in s4.iter().enumerate() {
                            out.push_str(&format!("{}, ", byte));
                            if (i + 1) % 12 == 0 {
                                out.push_str("\n    ");
                            }
                        }
                        out.push_str("\n];\n\n");
                    } else {
                        out.push_str(&format!(
                            "static {}_WEIGHTS_S8: [i8; {}] = [\n    ",
                            prefix,
                            weights.len()
                        ));
                        for (i, byte) in weights.iter().enumerate() {
                            out.push_str(&format!("{}, ", byte));
                            if (i + 1) % 12 == 0 {
                                out.push_str("\n    ");
                            }
                        }
                        out.push_str("\n];\n\n");
                    }

                    if let Some(b) = bias {
                        out.push_str(&format!(
                            "static {}_BIAS_S32: [i32; {}] = [\n    ",
                            prefix,
                            b.len()
                        ));
                        for (i, val) in b.iter().enumerate() {
                            out.push_str(&format!("{}, ", val));
                            if (i + 1) % 8 == 0 {
                                out.push_str("\n    ");
                            }
                        }
                        out.push_str("\n];\n\n");
                    }
                }
                _ => {}
            }
        }

        // Emit struct definition
        let input_tensor_id = graph.inputs.first().copied().unwrap_or(0);
        let input_tensor = graph
            .tensors
            .iter()
            .find(|t| t.id == input_tensor_id)
            .unwrap();
        let input_len = input_tensor.shape.total_elements();

        let output_tensor_id = graph.outputs.first().copied().unwrap_or(0);
        let output_tensor = graph
            .tensors
            .iter()
            .find(|t| t.id == output_tensor_id)
            .unwrap();
        let output_len = output_tensor.shape.total_elements();

        out.push_str(&format!("pub struct {};\n\n", self.struct_name));
        out.push_str(&format!("impl {} {{\n", self.struct_name));
        out.push_str(&format!(
            "    pub const INPUT_DIM: usize = {};\n",
            input_len
        ));
        out.push_str(&format!(
            "    pub const OUTPUT_DIM: usize = {};\n",
            output_len
        ));
        out.push_str(&format!(
            "    pub const ARENA_SIZE: usize = ARENA_SIZE_BYTES;\n\n"
        ));

        // Predict method
        out.push_str("    pub fn predict<'a>(\n");
        out.push_str("        input: &[i8],\n");
        out.push_str("        arena: &'a mut [u8; ARENA_SIZE_BYTES],\n");
        out.push_str("    ) -> Result<&'a [i8], &'static str> {\n");
        out.push_str(&format!("        if input.len() != {} {{\n", input_len));
        out.push_str("            return Err(\"Invalid input length\");\n");
        out.push_str("        }\n\n");

        // Copy input to input buffer offset in arena
        let input_offset = arena_plan.offset_of(input_tensor_id).unwrap_or(0);
        out.push_str(&format!(
            "        // Copy input into arena buffer (offset {})\n",
            input_offset
        ));
        out.push_str(&format!(
            "        let input_slice = unsafe {{ core::slice::from_raw_parts_mut(arena.as_mut_ptr().add({}) as *mut i8, {}) }};\n",
            input_offset, input_len
        ));
        out.push_str("        input_slice.copy_from_slice(input);\n\n");

        // Emit layer execution calls
        for layer in &graph.layers {
            let in_id = layer.inputs[0];
            let out_id = layer.outputs[0];
            let in_offset = arena_plan.offset_of(in_id).unwrap_or(0);
            let out_offset = arena_plan.offset_of(out_id).unwrap_or(0);

            let in_t = graph.tensors.iter().find(|t| t.id == in_id).unwrap();
            let out_t = graph.tensors.iter().find(|t| t.id == out_id).unwrap();
            let in_len = in_t.shape.total_elements();
            let out_len = out_t.shape.total_elements();
            let prefix = layer.name.to_uppercase();

            out.push_str(&format!("        // Layer: {}\n", layer.name));
            out.push_str(&format!(
                "        let in_buf = unsafe {{ core::slice::from_raw_parts(arena.as_ptr().add({}) as *const i8, {}) }};\n",
                in_offset, in_len
            ));
            out.push_str(&format!(
                "        let out_buf = unsafe {{ core::slice::from_raw_parts_mut(arena.as_mut_ptr().add({}) as *mut i8, {}) }};\n",
                out_offset, out_len
            ));

            match &layer.op {
                OpPayload::FullyConnected {
                    packed_s4, bias, ..
                } => {
                    let bias_ref = if bias.is_some() {
                        format!("Some(&{}_BIAS_S32)", prefix)
                    } else {
                        "None".into()
                    };

                    out.push_str("        let fc_params = FcParams {\n");
                    out.push_str("            input_offset: 0,\n");
                    out.push_str("            filter_offset: 0,\n");
                    out.push_str("            output_offset: 0,\n");
                    out.push_str("            activation: Activation::int8_unconstrained(),\n");
                    out.push_str("        };\n");
                    out.push_str(&format!(
                        "        let quant_params = PerTensorQuantParams::new({}, {});\n",
                        out_t.quant.multiplier, out_t.quant.shift
                    ));

                    if packed_s4.is_some() {
                        out.push_str(&format!(
                            "        fully_connected_s4(\n            &fc_params,\n            &quant_params,\n            &Dims::new(1, 1, 1, {}),\n            in_buf,\n            &Dims::new({}, 1, 1, 1),\n            &{}_WEIGHTS_S4,\n            {},\n            &Dims::new(1, 1, 1, {}),\n            out_buf,\n        ).map_err(|_| \"FC s4 execution failed\")?;\n\n",
                            in_len, out_len, prefix, bias_ref, out_len
                        ));
                    } else {
                        out.push_str(&format!(
                            "        fully_connected_s8(\n            &fc_params,\n            &quant_params,\n            &Dims::new(1, 1, 1, {}),\n            in_buf,\n            &Dims::new({}, 1, 1, 1),\n            &{}_WEIGHTS_S8,\n            {},\n            &Dims::new(1, 1, 1, {}),\n            out_buf,\n        ).map_err(|_| \"FC s8 execution failed\")?;\n\n",
                            in_len, out_len, prefix, bias_ref, out_len
                        ));
                    }
                }
                OpPayload::Softmax => {
                    out.push_str(&format!(
                        "        softmax_s8(\n            &Dims::new(1, 1, 1, {}),\n            in_buf,\n            1073741824,\n            0,\n            0,\n            out_buf,\n        ).map_err(|_| \"Softmax s8 execution failed\")?;\n\n",
                        in_len
                    ));
                }
                _ => {}
            }
        }

        // Return slice pointing to output buffer inside arena
        let final_out_offset = arena_plan.offset_of(output_tensor_id).unwrap_or(0);
        out.push_str(&format!(
            "        let result = unsafe {{ core::slice::from_raw_parts(arena.as_ptr().add({}) as *const i8, {}) }};\n",
            final_out_offset, output_len
        ));
        out.push_str("        Ok(result)\n");
        out.push_str("    }\n");
        out.push_str("}\n");

        out
    }
}
