/* ===========================================================================
 * Auto-generated by embedded-nn C99 Code Generator
 * Model: GestureModel
 * Zero dynamic allocation. Fully static arena execution.
 * =========================================================================== */

#ifndef GESTUREMODEL_H
#define GESTUREMODEL_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#define GESTUREMODEL_ARENA_SIZE_BYTES 32
#define GESTUREMODEL_INPUT_DIM 16
#define GESTUREMODEL_OUTPUT_DIM 2

/* Static Model Weights */
static const int8_t GESTUREMODEL_LAYER0_WEIGHTS[32] = {
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4
};

static const int32_t GESTUREMODEL_LAYER0_BIAS[2] = {
    0, 0
};

/* Math & Quantization Primitives */
static inline int32_t embedded_nn_doubling_high_mult(int32_t a, int32_t b) {
    bool overflow = (a == (int32_t)0x80000000 && b == (int32_t)0x80000000);
    int64_t prod = (int64_t)a * (int64_t)b;
    int32_t high = (int32_t)((prod + (1LL << 30)) >> 31);
    return overflow ? 0x7FFFFFFF : high;
}

static inline int32_t embedded_nn_requantize(int32_t val, int32_t mult, int32_t shift) {
    int32_t total_shift = 31 - shift;
    int64_t round = 1LL << (total_shift - 1);
    int64_t prod = (int64_t)val * (int64_t)mult + round;
    return (int32_t)(prod >> total_shift);
}

static inline int32_t embedded_nn_clamp(int32_t val, int32_t min, int32_t max) {
    if (val < min) return min;
    if (val > max) return max;
    return val;
}

static inline void embedded_nn_relu_s8(int8_t *data, size_t size) {
    for (size_t i = 0; i < size; i++) {
        if (data[i] < 0) data[i] = 0;
    }
}

static inline void embedded_nn_fully_connected_s8(
    const int8_t *input,
    size_t in_dim,
    const int8_t *weights,
    const int32_t *bias,
    size_t out_dim,
    int32_t input_offset,
    int32_t output_offset,
    int32_t mult,
    int32_t shift,
    int32_t act_min,
    int32_t act_max,
    int8_t *output
) {
    for (size_t out_c = 0; out_c < out_dim; out_c++) {
        int32_t acc = (bias != NULL) ? bias[out_c] : 0;
        const int8_t *w_row = &weights[out_c * in_dim];
        for (size_t in_c = 0; in_c < in_dim; in_c++) {
            int32_t in_val = (int32_t)input[in_c] + input_offset;
            int32_t w_val = (int32_t)w_row[in_c];
            acc += in_val * w_val;
        }
        acc = embedded_nn_requantize(acc, mult, shift);
        acc += output_offset;
        acc = embedded_nn_clamp(acc, act_min, act_max);
        output[out_c] = (int8_t)acc;
    }
}

/**
 * @brief Executes model forward pass with zero dynamic memory allocation.
 *
 * @param input   Pointer to INT8 input tensor of size GESTUREMODEL_INPUT_DIM.
 * @param output  Pointer to INT8 output buffer of size GESTUREMODEL_OUTPUT_DIM.
 * @param arena   Pointer to static SRAM memory arena of size GESTUREMODEL_ARENA_SIZE_BYTES.
 * @return 0 on success, non-zero on failure.
 */
static inline int gesturemodel_predict(
    const int8_t *input,
    int8_t *output,
    uint8_t *arena
) {
    if (!input || !output || !arena) {
        return -1;
    }

    embedded_nn_fully_connected_s8(
        input,
        GESTUREMODEL_INPUT_DIM,
        GESTUREMODEL_LAYER0_WEIGHTS,
        GESTUREMODEL_LAYER0_BIAS,
        GESTUREMODEL_OUTPUT_DIM,
        0,
        0,
        1073741824,
        0,
        -128,
        127,
        output
    );

    return 0;
}

#endif /* GESTUREMODEL_H */
