[package]
name = "embedded-nn-aton"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Open-source ST Neural-ART (ATON) NPU compiler and Epoch Controller binary assembler"

[dependencies]
embedded-nn-compiler = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
byteorder = "1.5"

[dev-dependencies]
embedded-nn = { workspace = true }
embedded-nn-tflite = { workspace = true }
